name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4.1.2
        name: Checkout de Repositório
      - name: Autenticação Docker 
        uses: docker/login-action@v3.1.0
        with: 
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      - name: Contrução da Imagem Docker
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            fernandohs99/devops4devs-news:v6
            fernandohs99/devops4devs-news:${{github.run_number}}

  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.2
        name: Checkout de Repositório
      - name: Configure Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Azure subscription
        run: az account set --subscription 02335d35-175a-4e9b-95d6-e76b6f525ba6

      - name: Get AKS credentials
        run: az aks get-credentials --resource-group RG-KUBERNETES --name azcluster-devops4devs --overwrite-existing

      - name: Atualização do Manifesto
        shell: bash
        run: |
          sed -i "s#{{AWS_ACCESS_KEY}}#${{ secrets.AWS_ACCESS_KEY }}#g" ./k8s/deployment.yaml
          sed -i "s#{{AWS_ACCESS_SECRET}}#${{ secrets.AWS_ACCESS_SECRET }}#g" ./k8s/deployment.yaml
          
      - name: Executar Deploy
        uses: Azure/k8s-deploy@v4.9
        with: 
          manifests: 
            ./k8s/deployment.yaml
            ./k8s/prometheus.yaml
          images: |
            fernandohs99/devops4devs-news:${{github.run_number}}
