name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps: 
      - name: Contrução da Imagem Docker
        run: echo "Docker Build"
      - name: "Publicar Imagem no Docker Hub"
        run: echo:"Docker Push"

  CD:
    runs-on: ubuntu-latest
    steps:
      - name: Conectar com Kubernetes
        run: echo "Configuração do KubeConfig"
      - name: Executar o Deploy
        run: echo "Kubectl Apply"
